apiVersion: v1
kind: Service
metadata:
  name: pregao
  labels:
    app.kubernetes.io/name: pregao
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pregao
  ports:
    - name: grpc
      port: 50053
      targetPort: grpc
      appProtocol: grpc
    - name: http
      port: 8080
      targetPort: http
